# permissions for end users to edit componenttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: componenttemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eck-custom-resources
    app.kubernetes.io/part-of: eck-custom-resources
    app.kubernetes.io/managed-by: kustomize
  name: componenttemplate-editor-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - componenttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - componenttemplates/status
  verbs:
  - get
