apiVersion: es.eck.github.com/v1alpha1
kind: IndexTemplate
metadata:
  name: indextemplate-sample
spec:
  dependsOn:
    indexTemplates:
      - indexTemplateName: indextemplate-base-sample
    indices:
      - indexName: index-base-sample
  body: |
    {
      "index_patterns" : ["index-*"],
      "priority" : 1,
      "template": {
        "settings" : {
          "number_of_shards" : 2,
          "number_of_replicas" : 0
        }
      }
    }
