apiVersion: v1
kind: Secret
metadata:
  name: elasticsearchuser-secret
type: Opaque
data:
  elasticsearchuser-sample: sample.password

---
apiVersion: es.eck.github.com/v1alpha1
kind: ElasticsearchUser
metadata:
  name: elasticsearchuser-sample
spec:
  secretName: elasticsearchuser-secret
  body: |
    {
      "roles" : [ "admin", "elasticsearchrole-sample" ],
      "full_name" : "Richard Feynman",
      "email" : "rfeynman@example.com",
      "metadata" : {
        "intelligence" : 7
      }
    }
