apiVersion: kibana.eck.github.com/v1alpha1
kind: Space
metadata:
  name: space-sample
spec:
  body: |
    {
      "name": "ECK Space sample",
      "description" : "This space was created using ECK-CR operator",
      "color": "#aabbcc",
      "initials": "CR",
      "disabledFeatures": [],
      "imageUrl": ""
    }
